### ISSUE TITLE
How to pass state through lexer?

### ISSUE THREAD

**Issue by Dolfik1** [xp44mm/FslexFsyacc#1]
I trying to parse Telegram's [TL language](https://core.telegram.org/mtproto/TL#overview). There are functions and types separated by sections. For example:

```
---types---
inputPeerEmpty#7f3b18ea = InputPeer;

---functions---
getUser#b0f732d5 int = User;
```

Here is part of my lexer:

```
rule read section =
  parse
  | "---"name+"---"   { read (lexeme lexbuf) lexbuf }
  | whitespace            { read section lexbuf }
  | name+                   { NAME(lexeme lexbuf, section) }
```

I want to pass current `section` value together with name of type/function. How to achieve this? My lexer matches the section name, but I still get default value in the `NAME` case.

**Comment by xp44mm** [comment]
It is easy to realize your requirements with FslexFsyacc. Please refer to these two projects. If you are familiar with xUnit, JSON, HTML.

- [FSharp.HTML](https://github.com/xp44mm/FSharp.HTML)

- [UnquotedJson](https://github.com/xp44mm/UnquotedJson)

**Comment by abelbraaksma** [comment]
@Dolfik1, not sure this repo is a fork or not of the [original FsLexYacc](https://github.com/fsprojects/FsLexYacc) that's used by the F# compiler itself and the like, but you may have a look at [the documentation there](https://fsprojects.github.io/FsLexYacc/), which comes with extensive examples.

I'd assume this library will work somewhat similar.
